version: '3.8'

services:
  # helper to fix permissions on docker volumes
  init-chmod:
    image: alpine:latest
    container_name: tts-server_init
    command: sh -c "chmod -R 777 /etc/owntone /var/cache/owntone /srv/media"
    volumes:
      - ./owntone/etc:/etc/owntone
      - ./owntone/cache:/var/cache/owntone
      - ./owntone/tts:/srv/media

  tts-api:
    image: docker.io/tranphuongbinh/tts-api
    container_name: tts-server_tts-api
    ports:
      - "8001:8000"
    volumes:
      - ./tts-api/models:/app/models
    environment:
      - MODEL_DIR=/app/models
    restart: always
    depends_on:
      init-chmod:
        condition: service_completed_successfully

  owntone:
    image: docker.io/owntone/owntone:latest
    container_name: tts-server_owntone
    network_mode: host
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - ./owntone/etc:/etc/owntone
      - ./owntone/tts:/srv/media
      - ./owntone/cache:/var/cache/owntone
    restart: unless-stopped
    depends_on:
      init-chmod:
        condition: service_completed_successfully
